config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers,skip: [:passwords], controllers: {
   sessions:      'public/sessions',
   registrations: 'public/registrations'
  }

  namespace :admin do
    root 'homes#top'
    get '/orders/:id' => 'orders#show'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'orders/order_id/order_detatils/:id' => 'orders#update'
  end

  scope module: :public do
    get 'search' => 'items#search'
    root 'homes#top'
    get '/about'=>'homes#about'
    get '/thanks'=>'homes#thanks'
    resources :genres, only: [:show]
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show', as: :mypage
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    patch 'customers/withdraw'=>'customers#withdraw'
    get 'publics/edit'=>'customers#edit'
    patch 'customers/update'=>'customers#update'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/confirm' => 'orders/confirm'
    get 'orders/complete' => 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :amount, presence: true
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true


  # attachment :profile_image

  # validates :name, presence: true, length: {in:2..20}
  # validates :name, uniqueness: true
  # validates :introduction, length: {maximum: 50}
end

app/models/genre.rb
class Genre < ApplicationRecord
  # has_many :items, dependent: :destroy
  validates :name, presence: true
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :tables
  has_many :order_details
  belongs_to :genre

  def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :orders_details, dependent: :destroy
  enum payment: [:クレジットカード, :銀行振込]
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum asdf: [:ご自身の住所, :登録済住所から選択, :新しいお届け先]
  enum select_address: { my_address: 0, registered_address: 1, new_address: 2 }
  enum qwer: [:入金待ち, :入金確認中, :製作中, :発送準備中, :発送済み]
  enum order_status: {}
  validates :total_payment, presence: true
  validates :shipping_cost, presence: true
  def sum_amount
    sum = 0
    self.orders_details.each do |detail|
      sum += detail.amount
    end
    return sum
  end
end

app/models/orders_detail.rb
class OrdersDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
before_action :authenticate_admin!

  def top
    #@orders = Order.all
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      redirect_to new_admin_item_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
   if @item.update(item_params)
    redirect_to admin_item_path(@item)
   else
    render "edit"
   end
  end

  private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :genre_id, :id_active, :created_at, :updated_at)
  end

  def genre_params
    params.require(:genre).permit(:genre_id, :name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_customer!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource)
    if resource == :admin
     new_admin_session_path
    else
     root_path
    end
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path
    elsif resource.is_a?(Customer)
      mypage_path
    end
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/items/edit.html.erb
<div class = "container">
  <div class = "row">
   <h2>商品編集</h2>
  </div>

  <div class = "row mt-3">
   <dic class = "offset-3">
    <table class = "table-borderless">
     <%= form_with model:@item, url: admin_item_path, method: :patch, local:true do |f| %>
     <tr>
      <td><%= f.label :商品画像 %></td>
      <td><%= f.attachment_field :image %></td>
     </tr>
     <tr>
      <td><%= f.label :商品名 %></td>
      <td><%= f.text_field :name %></td>
     </tr>
     <tr>
      <td><%= f.label :商品説明 %></td>
      <td><%= f.text_area :introduction %></td>
     </tr>
     <tr>
      <td>ジャンル</td>
      <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
     </tr>
     <tr>
      <td><%= f.label :税抜価格 %></td>
      <td><%= f.text_field :price %></td>
     </tr>
     <tr>
      <td><%= f.label :販売ステータス %></td>
      <td class="select_field">
						<%= f.radio_button :is_active, true %>
						<%= f.label :is_active, "販売中", class: "text-active" %>
						<%= f.radio_button :is_active, false %>
						<%= f.label :is_active, "販売停止中", class: "text-invalid" %>
					</td>
     </tr>
    </table>
   </div>
  </div>

  <div class = "row mt-3">
   <dic class = "offset-3">
    <%= f.submit :変更を保存, class:"btn btn-success" %>
      <% end %>
      </div>
      </div>
      </div>

app/views/admin/items/index.html.erb
 <h2>商品一覧</h2>
 <%= link_to "+", new_admin_item_path(@item), class: "btn shadow-sm" %>

<table class = "table text-center">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= link_to item.name, admin_item_path(item) %></td>
      <td><%= item.price %></td>
      <td><%= item.genre.name %></td>
      <td>
					<% if item.is_active? %>
						<span class="text-active">販売中</span>
					<% else %>
						<span class="text-invalid">販売停止中</span>
					<% end %>
				</td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<div class = "container">
 <div class = "row">
  <h2>商品新規登録</h2>
 </div>

 <div class = "row mt-3">
  <div class = "offset-3">
   <table class = "table-borderless">
    <%= form_with model:@item, url: admin_items_path, local:true do |f| %>
     <tr>
      <td><%= f.label :商品画像 %></td>
      <td><%= f.attachment_field :image %></td>
     </tr>
     <tr>
      <td><%= f.label :商品名 %></td>
      <td><%= f.text_field :name %></td>
     </tr>
     <tr>
      <td><%= f.label :商品説明 %></td>
      <td><%= f.text_area :introduction %></td>
     </tr>
     <tr>
      <td><%= f.label :ジャンル %></td>
      <td class = "select_field" ><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
     </tr>
     <tr>
      <td><%= f.label :税抜価格 %></td>
      <td><%= f.number_field :price %></td>
     </tr>
     <tr>
      <td><%= f.label :sales_status, "販売ステータス" %></td>
					<td class="select_field">
						<%= f.radio_button :is_active, true %>
						<%= f.label :is_active, "販売中", class: "text-active" %>
						<%= f.radio_button :is_active, false %>
						<%= f.label :is_active, "販売停止中", class: "text-invalid" %>
					</td>
     </tr>
    </table>

     <div class = "row flex aligncenter p15">
      <%= f.submit :新規登録, class: "btn btn-success" %>
      <% end %>
     </div>
    </div>
   </div>
</div>

app/views/admin/items/show.html.erb
<div class = "container my-5">
 <div class = "row">

 <h2>商品詳細</h2>
 </div>

<div class = "row mt-3">
 <div class = "offset-sm-1 col-sm-3">
 <%= attachment_image_tag @item, :image, size: "200x200", fallback: 'no_image.jpeg' %>
  </div>
  <div class = "col-sm-4">
<table class = "table-borderless">
  <tbody>
    <tr>
      <td>商品名</td>
      <td><%= @item.name %></td></tr>

      <tr><td>商品説明</td>
      <td><%= @item.introduction %></td></tr>
      <tr>
        <td>ジャンル</td>
        <td><%= link_to @item.genre.name, admin_genres_path(genre_id: @item.genre_id), class: "underline" %></td>
      </tr>

      <tr><td>税込価格（税抜価格）</td>
      <td><%= @item.price %>円</td></tr>
      <tr>
        <td>販売ステータス</td>
        <td>
						<% if @item.is_active? %>
							<span class="text-active">販売中</span>
						<% else %>
							<span class="text-invalid">販売停止中</span>
						<% end %>
      </tr>

  </tbody>
</table>
</div>
</div>

<div class = "row">
  <div class = "offset-sm-1">
<%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
<!--</div>-->
</div>
</div>