config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers,skip: [:passwords], controllers: {
   sessions:      'public/sessions',
   registrations: 'public/registrations'
  }

  namespace :admin do
    root 'homes#top'
    get '/orders/:id' => 'orders#show'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'orders/order_id/order_detatils/:id' => 'orders#update'
  end

  scope module: :public do
    get 'search' => 'items#search'
    root 'homes#top'
    get '/about'=>'homes#about'
    get '/thanks'=>'homes#thanks'
    resources :genres, only: [:show]
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show', as: :mypage
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    patch 'customers/withdraw'=>'customers#withdraw'
    get 'publics/edit'=>'customers#edit'
    patch 'customers/update'=>'customers#update'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/confirm' => 'orders/confirm'
    get 'orders/complete' => 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true


  # attachment :profile_image

  # validates :name, presence: true, length: {in:2..20}
  # validates :name, uniqueness: true
  # validates :introduction, length: {maximum: 50}
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    if @customer = Customer.find(params[:id])
       @customer.update(customer_params)
       redirect_to admin_customers_path
    else
       flash[:notice] = "正しく保存できませんでした。"
       redirect_to edit_admin_customers_path(@customer)
    end
  end

 private
 def customer_params
   params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_valid)
 end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/customers/index.html.erb
<div class = "container my-5">
  <div class = "row">
    <h2>会員一覧</h2>
  </div>

  <div class = "row mt-3">
    <div class = "offset-sm-1 col-sm-10">
      <table class = "table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
          </tr>
        </thead>

        <tbody>
          <% @customer.each do |customer| %>
            <tr>
              <td><%= customer.id %></td>
              <td>
              <%= link_to admin_customers_path(customer) do %>
              <%= customer.last_name %><%= customer.first_name %></td>
              <td><%= customer.email %></td>
              </tr>
              <% end %>
         </tbody>
      </table>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<divclass = "container my-5">
  <divclass = "row">
    <h2><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</h2>
  </div>

  <divclass = "row mt-3">
    <divclass = "offset-sm-1 col-sm-7">
      <tableclass = "table table-borderless">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %>
                </div>
              <% end %>
            </div>
            </td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %><%= @customer.first_name %></td>
          </tr>

          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
          </tr>

          <tr>
            <td>郵便番号</td>
            <td><%= @customer.postal_code %></td>
          </tr>

          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>

          <tr>
            <td>電話番号</td>
            <td><%= @customer.telephone_number %></td>
          </tr>

          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
        </tbody>
      </table>
    </div>

    <divclass = "col-sm-3 my-auto">
      <%=link_to "編集する", edit_admin_customer_path, class: "btn btn-success" %>
      <%=link_to "注文履歴一覧を見る", admin_customer_orders_path, class: "btn btn-primary mt-5" %>
    </div>
  </div>
</div>