config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers,skip: [:passwords], controllers: {
   sessions:      'public/sessions',
   registrations: 'public/registrations'
  }

  namespace :admin do
    root 'homes#top'
    get '/orders/:id' => 'orders#show'
    resources :items, except: [:destroy]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    patch 'orders/order_id/order_detatils/:id' => 'orders#update'
  end

  scope module: :public do
    get 'search' => 'items#search'
    root 'homes#top'
    get '/about'=>'homes#about'
    get '/thanks'=>'homes#thanks'
    resources :genres, only: [:show]
    resources :items, only: [:index, :show]
    get 'customers/my_page' => 'customers#show', as: :mypage
    get 'customers/unsubscribe'=>'customers#unsubscribe'
    patch 'customers/withdraw'=>'customers#withdraw'
    get 'publics/edit'=>'customers#edit'
    patch 'customers/update'=>'customers#update'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    post 'orders/confirm' => 'orders/confirm'
    get 'orders/complete' => 'orders/complete'
    resources :orders, only: [:new, :create, :index, :show]
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]

  end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  validates :amount, presence: true
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true


  # attachment :profile_image

  # validates :name, presence: true, length: {in:2..20}
  # validates :name, uniqueness: true
  # validates :introduction, length: {maximum: 50}
end

app/models/genre.rb
class Genre < ApplicationRecord
  # has_many :items, dependent: :destroy
  validates :name, presence: true
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  attachment :image
  has_many :cart_items, dependent: :destroy
  has_many :tables
  has_many :order_details
  belongs_to :genre

  def self.search(keyword)
  where(["name like?", "%#{keyword}%"])
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :orders_details, dependent: :destroy
  enum payment: [:クレジットカード, :銀行振込]
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum asdf: [:ご自身の住所, :登録済住所から選択, :新しいお届け先]
  enum select_address: { my_address: 0, registered_address: 1, new_address: 2 }
  enum qwer: [:入金待ち, :入金確認中, :製作中, :発送準備中, :発送済み]
  enum order_status: {}
  validates :total_payment, presence: true
  validates :shipping_cost, presence: true
  def sum_amount
    sum = 0
    self.orders_details.each do |detail|
      sum += detail.amount
    end
    return sum
  end
end

app/models/orders_detail.rb
class OrdersDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_customer!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_out_path_for(resource)
    if resource == :admin
     new_admin_session_path
    else
     root_path
    end
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_root_path
    elsif resource.is_a?(Customer)
      mypage_path
    end
  end



  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
  <header>
     <nav class="navbar navbar-expand-lg">
        <div class="container">

    <div style="padding:28px;"><%= image_tag "05.jpeg", size: "65x65" %></div>
    <ul class = "navbar-nav ml-auto">
  <% if admin_signed_in? %>
    <li>
      <%= link_to '商品一覧', admin_items_path, class: 'nav-link' %>
    </li>
     <li>
       <%= link_to '会員一覧', admin_customers_path, class: "nav-link" %>
     </li>
     <li>
       <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %>
     </li>
     <li>
       <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
     </li>
    <li>
    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "nav-link" %>
    </li>

    <% elsif customer_signed_in? %>
        <li>
      <%= link_to 'マイページ', mypage_path, class: 'nav-link' %>
    </li>
     <li>
       <%= link_to '商品一覧', items_path, class: "nav-link" %>
     </li>
     <li>
       <%= link_to "カート", cart_items_path, class: "nav-link" %>
     </li>
    <li>
    <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "nav-link" %>
    </li>

     <% else %>
    <li>
      <%= link_to 'About', about_path, class: 'nav-link' %>
    </li>
     <li>
       <%= link_to '商品一覧', items_path, class: "nav-link" %>
     </li>
     <li>
       <%= link_to "新規登録", new_customer_registration_path, class: "nav-link" %>
     </li>
    <li>
    <%= link_to 'ログイン', new_customer_session_path, class: "nav-link" %>
    </li>
  <% end %>
    </div>
    </div>
    </nav>
    <div class="search-form">
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<div class="post-list">
  <%# @items.each do |item| %>
    <%#= item.name %>
  <%# end %>
</div>
    </header>
      <%= yield %>
    </body>

</html>